# An example of a services.yaml file in an extension

services:
  BoltCachebuster\Twig:
    autowire: true
    autoconfigure: true
    bind:
      $secret: '%env(APP_SECRET)%'
    tags: ['twig.extension']
